'use strict';

// TODO group into mausritter, other, custom
const defaultImages = [
    ['None', ''],
    ['Mussel', 'Muscle.png'],
    ['Electric Lantern', 'item-electric-lantern.png'],
    ['Warhammer (Heavy)', 'item-heavy-1.png'],
    ['Spear (Heavy)', 'item-heavy-2.png'],
    ['Hookarm (Heavy)', 'item-heavy-3.png'],
    ['Heavy Armour', 'item-heavy-armour.png'],
    ['Bow (Heavy)', 'item-heavy-ranged.png'],
    //['Item 1', 'item-improvised.png'],
    ['Stick', 'item-imrpovised.png'],
    ['Lantern', 'item-lantern.png'],
    ['Dagger (Light)', 'item-light-1.png'],
    ['Needle (Light)', 'item-light-2.png'],
    ['Light Armour', 'item-light-armour.png'],
    ['Sling (Light)', 'item-light-ranged.png'],
    ['Axe (Medium)', 'item-medium-1.png'],
    ['Sword (Medium)', 'item-medium-2.png'],
    ['Mace (Medium)', 'item-medium-3.png'],
    ['Pip Purse', 'item-pips.png'],
    ['Arrows', 'item-quiver.png'],
    ['Rations', 'item-rations.png'],
    ['Spell 1', 'item-spell-1.png'],
    ['Spell 2', 'item-spell-2.png'],
    ['Spell 3', 'item-spell-3.png'],
    ['Spell 4', 'item-spell-4.png'],
    ['Spell 5', 'item-spell-5.png'],
    ['Stones', 'item-stones.png'],
    ['Torch', 'item-torch.png'],
    ['Limpet', 'limpet.png'],
    ['Razor Clam', 'razor_shell_8271_lg.png'],
    ['Twine', 'ball-of-hemp-twine.jpg'],
    ['Net', 'net.jpg'],
];
