'use strict';

const itemDefault = {
    name: '',
    usage: 3,
    damage: '',
    armour: false,
    mechanicDetail: '',
    detailSummary: '',
    detailSpecifics: '',
    imageSource: '',
    scale: 100,
    nudgeX: 0,
    nudgeY: 0,
    rotate: 0,
    backgroundColour: '#ffffff',
    borderColour: '#000000',
    foregroundColour: '#000000',
    whiteUsage: false,
    width: 1,
    height: 1,
    divider: true,
    borderWidth: 2,
    star: false,
    freeFonts: false
};

const itemTemplates = {
    limpetshield: {
        ...itemDefault,
        name: 'Limpet Shield',
        usage: 3,
        damage: '1/2 def',
        armour: true,
        imageSource: 'limpet.png',
    },
    dagger: {
        ...itemDefault,
        name: 'Dagger',
        usage: 3,
        damage: 'd6',
        detailSummary: 'Light',
        imageSource: 'item-light-1.png',
        nudgeY: 10,
    },
    torches: {
        ...itemDefault,
        name: 'Torches',
        usage: 3,
        imageSource: 'item-torch.png',
    },
    rations: {
        ...itemDefault,
        name: 'Rations',
        usage: 3,
        nudgeY: 10,
        imageSource: 'item-rations.png',
    },
    sword: {
        ...itemDefault,
        name: 'Sword',
        usage: 3,
        damage: 'd6/d8',
        detailSummary: 'Medium',
        image: 'Sword',
        imageSource: 'item-medium-2.png',
        backgroundImage: 'paper.jpg',
        backgroundColour: '#bdb3a8',
        foregroundColour: '#000000',
    },
    armour: {
        ...itemDefault,
        name: 'Heavy armour',
        usage: 3,
        damage: '1 def',
        armour: true,
        image: 'Heavy armour',
        imageSource: 'item-heavy-armour.png',
        scale: 90,
        width: 1,
        height: 2,
    },
    mussel: {
        ...itemDefault,
        name: 'Mussel Armour',
        usage: 3,
        damage: '2 def',
        armour: true,
        mechanicDetail: 'Disadvantage on DEX saves, cannot run',
        detailSummary: 'Heavy',
        image: 'Heavy armour',
        imageSource: 'Muscle.png',
        width: 1,
        height: 2,
    },
    spell: {
        ...itemDefault,
        name: 'Restore',
        usage: 3,
        image: 'Spell 1',
        imageSource: 'item-spell-1.png',
        star: true,
    },
    condition: {
        ...itemDefault,
        name: 'Injured',
        mechanicDetail: 'Disadvantage on STR and DEX saves',
        detailSummary: 'Clear:',
        detailSpecifics: 'After full rest',
        backgroundColour: '#ff4444',
        foregroundColour: '#000000',
        divider: false,
    },
    condition2: {
        ...itemDefault,
        name: 'Frozen',
        usage: 6,
        mechanicDetail: 'You are frozen. Count turns in usage, dead when all used.',
        backgroundColour: '#384761',
        foregroundColour: '#ffffff',
        divider: true,
        borderWidth: 0,
    },
    razorclam: {
        ...itemDefault,
        name: 'Razor Clam',
        usage: 3,
        damage: 'd8',
        armour: false,
        mechanicDetail: 'Causes Irritated Injury on critical damage',
        detailSummary: 'Heavy',
        image: 'razor',
        imageSource: 'razor_shell_8271_lg.png',
        width: 1,
        height: 2,
        divider: true,
    },
    net: {
        ...itemDefault,
        name: 'Tough Net',
        image: 'net',
        imageSource: 'net.jpg',
    },
    rope: {
        ...itemDefault,
        name: 'Tough Rope',
        image: 'rope',
        imageSource: 'rope2.svg',
    },
    twine: {
        ...itemDefault,
        name: 'Twine',
        usage: 3,
        /* TODO better artwork */
        imageSource: 'ball-of-hemp-twine.jpg',
    },
    irritated: {
        ...itemDefault,
        name: 'Irritated Injury',
        mechanicDetail: 'Disadvantage on STR and DEX saves',
        detailSummary: 'Clear:',
        detailSpecifics: 'After two full rests',
        backgroundColour: '#cc5530',
        foregroundColour: '#000000',
        divider: false,
    }
};
