'use strict';

const itemTemplates = {
    limpetshield: {
        name: 'Limpet Shield',
        usage: 3,
        damage: '1/2 def',
        armour: true,
        mechanicDetail: '',
        clearDetail: '',
        classDetail: '',
        imageSource: 'limpet.png',
        backgroundColor: '#ffffff',
        foregroundColor: '#000000',
        width: 1,
        height: 1,
        divider: true,
        border: true,
        star: false,
    },
    dagger: {
        name: 'Dagger',
        usage: 3,
        damage: 'd6',
        armour: false,
        mechanicDetail: '',
        clearDetail: '',
        classDetail: 'Light',
        imageSource: 'item-light-1.png',
        nudgeY: 10,
        backgroundColor: '#ffffff',
        foregroundColor: '#000000',
        width: 1,
        height: 1,
        divider: true,
        border: true,
        star: false,
    },
    torches: {
        name: 'Torches',
        usage: 3,
        damage: '',
        armour: false,
        mechanicDetail: '',
        clearDetail: '',
        classDetail: '',
        imageSource: 'item-torch.png',
        backgroundColor: '#ffffff',
        foregroundColor: '#000000',
        width: 1,
        height: 1,
        divider: true,
        border: true,
        star: false,
    },
    rations: {
        name: 'Rations',
        usage: 3,
        damage: '',
        armour: false,
        mechanicDetail: '',
        clearDetail: '',
        classDetail: '',
        nudgeY: 10,
        imageSource: 'item-rations.png',
        backgroundColor: '#ffffff',
        foregroundColor: '#000000',
        width: 1,
        height: 1,
        divider: true,
        border: true,
        star: false,
    },
    sword: {
        name: 'Sword',
        usage: 3,
        damage: 'd6/d8',
        armour: false,
        mechanicDetail: '',
        clearDetail: '',
        classDetail: 'Medium',
        image: 'Sword',
        imageSource: 'item-medium-2.png',
        backgroundImage: 'paper.jpg',
        backgroundColor: '#bdb3a8',
        foregroundColor: '#000000',
        width: 1,
        height: 1,
        divider: true,
        border: true,
        star: false,
    },
    armour: {
        name: 'Heavy armour',
        usage: 3,
        damage: '1 def',
        armour: true,
        mechanicDetail: '',
        clearDetail: '',
        classDetail: 'Heavy',
        image: 'Heavy armour',
        imageSource: 'item-heavy-armour.png',
        backgroundColor: '#ffffff',
        foregroundColor: '#000000',
        width: 1,
        height: 2,
        divider: true,
        border: true,
        star: false,
    },
    mussel: {
        name: 'Mussel Armour',
        usage: 3,
        damage: '2 def',
        armour: true,
        mechanicDetail: 'Disadvantage on DEX saves, cannot run',
        clearDetail: '',
        classDetail: 'Heavy',
        image: 'Heavy armour',
        imageSource: 'muscle.png',
        backgroundColor: '#ffffff',
        foregroundColor: '#000000',
        width: 1,
        height: 2,
        divider: true,
        border: true,
        star: false,
    },
    spell: {
        name: 'Restore',
        usage: 3,
        damage: '',
        armour: false,
        mechanicDetail: '',
        clearDetail: '',
        classDetail: '',
        image: 'Spell 1',
        imageSource: 'spell-1.png',
        backgroundColor: '#ffffff',
        foregroundColor: '#000000',
        width: 1,
        height: 1,
        divider: true,
        border: true,
        star: true,
    },
    condition: {
        name: 'Injured',
        usage: 0,
        damage: '',
        armour: false,
        mechanicDetail: 'Disadvantage on STR and DEX saves',
        clearDetail: 'After full rest',
        classDetail: '',
        image: '',
        imageSource: '',
        backgroundColor: '#ff4444',
        foregroundColor: '#000000',
        width: 1,
        height: 1,
        divider: false,
        border: true,
        star: false,
    },
    condition2: {
        name: 'Frozen',
        usage: 6,
        damage: '',
        armour: false,
        mechanicDetail: 'You are frozen. Count turns in usage, dead when all used.',
        clearDetail: '',
        classDetail: '',
        image: '',
        imageSource: '',
        backgroundColor: '#384761',
        foregroundColor: '#ffffff',
        width: 1,
        height: 1,
        divider: true,
        border: false,
        star: false,
    },
    razorclam: {
        name: 'Razor Clam',
        usage: 3,
        damage: 'd8',
        armour: false,
        mechanicDetail: 'Causes Irritated Injury on critical damage',
        clearDetail: '',
        classDetail: 'Heavy',
        image: 'razor',
        imageSource: 'razor_shell_8271_lg.png',
        backgroundColor: '#ffffff',
        foregroundColor: '#000000',
        width: 1,
        height: 2,
        divider: true,
        border: true,
        star: false,
    },
    net: {
        name: 'Tough Net',
        usage: 0,
        damage: '',
        armour: false,
        mechanicDetail: '',
        clearDetail: '',
        classDetail: '',
        image: 'net',
        imageSource: 'net.jpg',
        backgroundColor: '#ffffff',
        foregroundColor: '#000000',
        width: 1,
        height: 1,
        divider: true,
        border: true,
        star: false,
    },
    rope: {
        name: 'Tough Rope',
        usage: 0,
        damage: '',
        armour: false,
        mechanicDetail: '',
        clearDetail: '',
        classDetail: '',
        image: 'rope',
        imageSource: 'rope2.svg',
        backgroundColor: '#ffffff',
        foregroundColor: '#000000',
        width: 1,
        height: 1,
        divider: true,
        border: true,
        star: false,
    },
    twine: {
        name: 'Twine',
        usage: 3,
        damage: '',
        armour: false,
        mechanicDetail: '',
        clearDetail: '',
        classDetail: '',
        /* TODO better artwork */
        imageSource: 'ball-of-hemp-twine.jpg',
        backgroundColor: '#ffffff',
        foregroundColor: '#000000',
        width: 1,
        height: 1,
        divider: true,
        border: true,
        star: false,
    },
    irritated: {
        name: 'Irritated Injury',
        usage: 0,
        damage: '',
        armour: false,
        mechanicDetail: 'Disadvantage on STR and DEX saves',
        clearDetail: 'After two full rests',
        classDetail: '',
        image: '',
        imageSource: '',
        backgroundColor: '#cc5530',
        foregroundColor: '#000000',
        width: 1,
        height: 1,
        divider: false,
        border: true,
        star: false,
    }
};
